server:
  port: 9000
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${REMOTE_HOST}:8848
      config:
        server-addr: ${REMOTE_HOST}:8848
        file-extension: yml